In [31]:
# importando os scripts de consulta

import sys
import os

# Altera o caminho para a pasta raiz do projeto (um nível acima)
raiz_projeto = os.path.abspath(os.path.join(os.getcwd(), ".."))

# Adiciona a raiz do projeto ao caminho de busca do Python se ainda não estiver lá
if raiz_projeto not in sys.path:
    sys.path.append(raiz_projeto)

    
import pandas as pd
from scripts.crm_inscricoes import load_inscricoes
from scripts.crm_leads import load_leads

In [32]:
leads = load_leads()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 250 registros
Página 18: 250 registros
Página 19: 250 registros
Página 20: 250 registros
Página 21: 250 registros
Página 22: 250 registros
Página 23: 250 registros
Página 24: 250 registros
Página 25: 250 registros
Página 26: 250 registros
Página 27: 250 registros
Página 28: 250 registros
Página 29: 250 registros
Página 30: 250 registros
Página 31: 250 registros
Página 32: 250 registros
Página 33: 135 registros

In [33]:
inscricoes = load_inscricoes()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 142 registros

In [34]:
leads.columns

Index(['Número Inscrição', 'cpf', 'Tabulação Realizada', 'Nome Completo',
       'Nome', 'Sobrenome', 'Email', 'Celular', 'Telefone', 'ID Lead',
       'Data Criação', 'Concurso Atual', 'Concurso de Origem', 'Oferta Atual',
       'Situação Funil', 'Unidade Lead', 'Linha de Negócio', 'Unidade Form',
       'Origem Lead', 'Última Tabulação', 'Proprietário', 'Nacionalidade',
       'Idade', 'Data Nascimento', 'Canal', 'RG', 'Estado Civil',
       'Órgão Expedidor', 'Sexo', 'Cor/Raça', 'Tabulação Lead',
       'Detalhamento Tabulação'],
      dtype='str')

In [35]:
inscricoes.columns

Index(['Situação Inscrição', 'Numero Inscricao', 'Nome Completo',
       'Situação de Avaliação', 'Curso ID', 'Unidade Inscrito',
       'Forma de Ingresso', 'createdon', 'cad_inscricaocandidatoid',
       'Data Aprovação', 'Data de Pagamento', 'Situação Pagamento'],
      dtype='str')

In [36]:
captacao = leads.merge(inscricoes, how='left', left_on='Número Inscrição', right_on='Numero Inscricao')

In [37]:
captacao.shape

(8135, 44)

In [38]:

url = 'https://docs.google.com/spreadsheets/d/13DBRdUsHT5wupKkq3Omi9VUr9Nj3R5gYVMfSSkmtXQM/export?format=xlsx'

matriculas_itabirito = pd.read_excel(url, sheet_name = "ITABIRITO")
matriculas_altamira = pd.read_excel(url, sheet_name = "ALTAMIRA")
matriculas_lorena = pd.read_excel(url, sheet_name = "LORENA")
matriculas_canaa = pd.read_excel(url, sheet_name = "Canaã")


matriculas = pd.concat([matriculas_itabirito, matriculas_altamira, matriculas_lorena, matriculas_canaa], ignore_index=True)

In [39]:
matriculas.shape

(1635, 23)

In [40]:
matriculas.dropna(inplace = True, subset = ['Número de Inscrição'])

In [41]:
print(f' Existem {matriculas.shape[0]} matrículas na planilha')

 Existem 765 matrículas na planilha

In [42]:
captacao.columns

Index(['Número Inscrição', 'cpf', 'Tabulação Realizada', 'Nome Completo_x',
       'Nome', 'Sobrenome', 'Email', 'Celular', 'Telefone', 'ID Lead',
       'Data Criação', 'Concurso Atual', 'Concurso de Origem', 'Oferta Atual',
       'Situação Funil', 'Unidade Lead', 'Linha de Negócio', 'Unidade Form',
       'Origem Lead', 'Última Tabulação', 'Proprietário', 'Nacionalidade',
       'Idade', 'Data Nascimento', 'Canal', 'RG', 'Estado Civil',
       'Órgão Expedidor', 'Sexo', 'Cor/Raça', 'Tabulação Lead',
       'Detalhamento Tabulação', 'Situação Inscrição', 'Numero Inscricao',
       'Nome Completo_y', 'Situação de Avaliação', 'Curso ID',
       'Unidade Inscrito', 'Forma de Ingresso', 'createdon',
       'cad_inscricaocandidatoid', 'Data Aprovação', 'Data de Pagamento',
       'Situação Pagamento'],
      dtype='str')

In [43]:
colunas_captacao = ['Nome Completo_x', 'cpf', 'ID Lead', 'Proprietário', 'Situação Inscrição', 'Número Inscrição', 'Unidade Lead', 'Unidade Form', 'Oferta Atual']
captacao = captacao[colunas_captacao]

In [44]:
# reitando Medicina 
captacao = captacao.loc[captacao['Oferta Atual'] != 'Medicina', :]

In [45]:
# retirando cursos livres

captacao = captacao.loc[captacao['Unidade Form'].str.contains('Cursos Livres') == False, :]

# Mapeando Matriculas entre as tabelas

In [46]:
matriculas_captacao = captacao.loc[captacao['Situação Inscrição'] == 'Matriculado']

In [47]:
matriculas_captacao.shape[0]

758

## Matriculas que estão no CRM, mas não estão na planilha

In [48]:
df = matriculas_captacao.loc[~matriculas_captacao['Número Inscrição'].isin(matriculas['Número de Inscrição'].str.strip())]
display(df)
df.shape

Empty DataFrame
Columns: [Nome Completo_x, cpf, ID Lead, Proprietário, Situação Inscrição, Número Inscrição, Unidade Lead, Unidade Form, Oferta Atual]
Index: []

(0, 9)

In [49]:
df.to_excel('matriculas_na_captacao_que_nao_estao_na_planilha.xlsx', index=False)

## Matriculas que estão na planilha, mas não estão no CRM

In [50]:
# padronização das colunas de inscricao

matriculas['Número de Inscrição'] = matriculas['Número de Inscrição'].str.strip()

matriculas_captacao['Número Inscrição'] = matriculas_captacao['Número Inscrição'].str.strip()

In [51]:
df = matriculas.loc[~matriculas['Número de Inscrição'].isin(matriculas_captacao['Número Inscrição'])]
# eliminar linhas em branco
df = df.dropna(subset=['Número de Inscrição'])
display(df)
df.shape

,CONSULTOR (a),DATA,Número de Inscrição,NOME,CELULAR,CPF (preencher apenas com números),CURSO,FORMA DE INGRESSO,1º Boleto alterado para 20/08?,% BOLSA CONCEDIDA,...,FORMA DE PAGAMNTO,QUANTIDADE DE PARCELAS,OBSERVAÇÃO,Unidade,Data e Hora,Unnamed: 18,DATA BOLETO AGOSTO (EXCEÇÕES),Unnamed: 15,Unnamed: 16,Unnamed: 17
277,Daniel,2026-07-28,CAN-004323-TRI,Mércia de Seles Guimarães,(93) 99204-3119,611.014.192-53,PSICOLOGIA,HISTORICO ESCOLAR,Não,0.7,...,PIX,NaN,NaN,Altamira,2026-07-28 17:24:04.680,NaN,NaT,NaN,NaN,NaT
321,Daniel,2026-08-11,CAN-005275-TRI,Pamela Alves da silva,91 9256-8834,032.812.862-75,NUTRIÇÃO,HISTORICO ESCOLAR,sim,0.7,...,PIX,NaN,NaN,Altamira,2026-08-11 10:30:14.863,NaN,NaT,NaN,NaN,NaT
414,Daniel,2026-06-26,CAN-002642-TRI,Jenifer Ramires Moura Lopes,(12) 99668-6354,478.204.298-10,NUTRIÇÃO,TRANSFERENCIA,Não,0.65,...,PIX,1 VEZ,NaN,Lorena,NaT,NaN,NaT,NaN,NaN,NaT
634,Duda,2026-08-13,CAN-005451-TRI,Joyce Aparecida de Oliveira Andrade,(12) 99233-9991,394.927.058-26,PSICOLOGIA,SEGUNDA GRADUAÇÃO,SIM,0.7,...,PIX,1 VEZ,NaN,Lorena,2026-08-13 15:06:59.154,NaN,NaT,NaN,NaN,NaT
635,Maria Rafaela,2026-08-13,CAN-005336-TRI,Alana Mara Silva Alves de Oliveira,(12) 98157-1409,467.136.658-45,ADMINISTRAÇÃO,HISTORICO ESCOLAR,ISENTA AGOSTO,0.65,...,BOLETO,1 VEZ,NaN,Lorena,2026-08-13 16:34:05.710,NaN,NaT,NaN,NaN,NaT
757,Flávia,2026-08-13,CAN-005439-TRI,Abner José de Castro Muniz,62 8106-2094,8503372169,Análise e Desenvolvimento de Sistemas,Histórico,NaN,0.6,...,Pix,NaN,NaN,NaN,NaT,NaN,NaT,NaN,Canaã,2026-08-13 13:30:26.236

(6, 23)

In [52]:
inscricoes.loc[inscricoes['Numero Inscricao'].isin(['CAN-004323-TRI', 'CAN-005275-TRI'])]

,Situação Inscrição,Numero Inscricao,Nome Completo,Situação de Avaliação,Curso ID,Unidade Inscrito,Forma de Ingresso,createdon,cad_inscricaocandidatoid,Data Aprovação,Data de Pagamento,Situação Pagamento
194,Matriculado,CAN-005275-TRI,Pamela Alves da Silva,Avaliado,Nutrição,NaN,Histórico Ensino Médio - Faculdade Serra Doura...,2026-08-11T10:26:51-03:00,{B11AE64E-8895-F111-B8DC-6045BD39BE00},NaN,2026-08-11T12:00:00-03:00,Pago
1115,Matriculado,CAN-004323-TRI,Mércia de Seles Guimarães,Avaliado,Psicologia,NaN,Histórico Ensino Médio - Faculdade Serra Doura...,2026-07-23T14:26:45-03:00,{971CAEA7-BB86-F111-AB0F-000D3AC0F764},2026-07-23T14:56:58-03:00,2026-07-28T00:00:00-03:00,Pago