In [43]:
# importando os scripts de consulta

import sys
import os

# Altera o caminho para a pasta raiz do projeto (um nível acima)
raiz_projeto = os.path.abspath(os.path.join(os.getcwd(), ".."))

# Adiciona a raiz do projeto ao caminho de busca do Python se ainda não estiver lá
if raiz_projeto not in sys.path:
    sys.path.append(raiz_projeto)

    
import pandas as pd
from scripts.crm_inscricoes import load_inscricoes
from scripts.crm_leads import load_leads

In [44]:
leads = load_leads()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 250 registros
Página 18: 250 registros
Página 19: 250 registros
Página 20: 250 registros
Página 21: 250 registros
Página 22: 250 registros
Página 23: 250 registros
Página 24: 250 registros
Página 25: 250 registros
Página 26: 250 registros
Página 27: 250 registros
Página 28: 250 registros
Página 29: 250 registros
Página 30: 250 registros
Página 31: 250 registros
Página 32: 250 registros
Página 33: 219 registros

In [45]:
inscricoes = load_inscricoes()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 208 registros

In [46]:
leads.columns

Index(['Inscrição Atual', 'cpf', 'Tabulação Realizada', 'Nome Completo',
       'Nome', 'Sobrenome', 'Email', 'Celular', 'Telefone', 'ID Lead',
       'Data Criação', 'Concurso Atual', 'Concurso de Origem', 'Oferta Atual',
       'Situação Funil', 'Unidade Lead', 'Linha de Negócio',
       'Última Tabulação', 'Idade', 'Data Nascimento', 'Proprietário', 'Sexo',
       'Nacionalidade', 'Unidade Form', 'Origem Lead', 'Canal', 'Estado Civil',
       'RG', 'Órgão Expedidor', 'Cor/Raça', 'Tabulação Lead',
       'Detalhamento Tabulação'],
      dtype='object')

In [47]:
inscricoes.columns

Index(['Situação Inscrição', 'Numero Inscricao', 'Nome Completo',
       'Situação de Avaliação', 'Curso ID', 'Unidade Inscrito',
       'Forma de Ingresso', 'createdon', 'cad_inscricaocandidatoid',
       'Data Aprovação', 'Data de Pagamento', 'Situação Pagamento'],
      dtype='object')

In [48]:
captacao = leads.merge(inscricoes, how='right', left_on='Inscrição Atual', right_on='Numero Inscricao')

In [49]:
captacao.shape

(4208, 44)

In [50]:

url = 'https://docs.google.com/spreadsheets/d/13DBRdUsHT5wupKkq3Omi9VUr9Nj3R5gYVMfSSkmtXQM/export?format=xlsx'

matriculas_itabirito = pd.read_excel(url, sheet_name = "ITABIRITO")
matriculas_altamira = pd.read_excel(url, sheet_name = "ALTAMIRA")
matriculas_lorena = pd.read_excel(url, sheet_name = "LORENA")
matriculas_canaa = pd.read_excel(url, sheet_name = "Canaã")


matriculas = pd.concat([matriculas_itabirito, matriculas_altamira, matriculas_lorena, matriculas_canaa], ignore_index=True)

In [51]:
matriculas.shape

(2505, 23)

In [52]:
matriculas.dropna(inplace = True, subset = ['Número de Inscrição'])

In [53]:
print(f' Existem {matriculas.shape[0]} matrículas na planilha')

 Existem 782 matrículas na planilha

In [54]:
captacao.columns

Index(['Inscrição Atual', 'cpf', 'Tabulação Realizada', 'Nome Completo_x',
       'Nome', 'Sobrenome', 'Email', 'Celular', 'Telefone', 'ID Lead',
       'Data Criação', 'Concurso Atual', 'Concurso de Origem', 'Oferta Atual',
       'Situação Funil', 'Unidade Lead', 'Linha de Negócio',
       'Última Tabulação', 'Idade', 'Data Nascimento', 'Proprietário', 'Sexo',
       'Nacionalidade', 'Unidade Form', 'Origem Lead', 'Canal', 'Estado Civil',
       'RG', 'Órgão Expedidor', 'Cor/Raça', 'Tabulação Lead',
       'Detalhamento Tabulação', 'Situação Inscrição', 'Numero Inscricao',
       'Nome Completo_y', 'Situação de Avaliação', 'Curso ID',
       'Unidade Inscrito', 'Forma de Ingresso', 'createdon',
       'cad_inscricaocandidatoid', 'Data Aprovação', 'Data de Pagamento',
       'Situação Pagamento'],
      dtype='object')

In [55]:
colunas_captacao = ['Nome Completo_x', 'cpf', 'ID Lead', 'Proprietário', 'Situação Inscrição', 'Inscrição Atual', 'Unidade Lead', 'Unidade Form', 'Oferta Atual']
captacao = captacao[colunas_captacao]

In [56]:
# reitando Medicina 
captacao = captacao.loc[captacao['Oferta Atual'] != 'Medicina', :]

In [57]:
# retirando cursos livres

captacao = captacao.loc[captacao['Unidade Form'].str.contains('Cursos Livres') == False, :]

# Mapeando Matriculas entre as tabelas

In [58]:
matriculas_inscricoes = inscricoes.loc[inscricoes['Situação Inscrição'] == 'Matriculado']
matriculas_inscricoes = matriculas_inscricoes.loc[matriculas_inscricoes['Curso ID'] != 'Medicina', :]

In [59]:
matriculas_inscricoes.shape[0]

787

## Matriculas que estão no CRM, mas não estão na planilha

In [68]:
df = matriculas_inscricoes.loc[~matriculas_inscricoes['Numero Inscricao'].isin(matriculas['Número de Inscrição'].str.strip())]
display(df)
df.shape

,Situação Inscrição,Numero Inscricao,Nome Completo,Situação de Avaliação,Curso ID,Unidade Inscrito,Forma de Ingresso,createdon,cad_inscricaocandidatoid,Data Aprovação,Data de Pagamento,Situação Pagamento
10,Matriculado,CAN-005526-TRI,Virginha de Nazaré Oliveira Ferreira,Apto para Avaliação,Biomedicina,NaN,Transferencia - Faculdade Serra Dourada Altamira,2026-08-14T11:29:54-03:00,{89206E9D-EC97-F111-B8DC-00224836B90D},2026-08-14T11:32:16-03:00,2026-08-14T03:00:00-03:00,Pago
59,Matriculado,CAN-005477-TRI,Vitória Maria Brito,Apto para Avaliação,Farmácia,NaN,Retorno - Faculdade Serra Dourada Altamira,2026-08-13T18:20:44-03:00,{D24E4ED6-5C97-F111-B8DC-7CED8DB11FB7},2026-08-13T18:23:10-03:00,2026-08-14T03:00:00-03:00,Pago
60,Matriculado,CAN-005476-TRI,Ana Carolina Domingues,Avaliado,Terapia Ocupacional,NaN,Histórico Ensino Médio - Faculdade Serra Doura...,2026-08-13T18:07:39-03:00,{A3AEAB02-5B97-F111-B8DC-000D3AC0F764},2026-08-13T18:09:34-03:00,2026-08-13T03:00:00-03:00,Pago
264,Matriculado,CAN-005271-TRI,Luciani Aparecida Lemes França Velloso,Avaliado,Nutrição,NaN,Histórico Ensino Médio - Faculdade Serra Doura...,2026-08-11T10:06:29-03:00,{149FAC73-8595-F111-B8DC-000D3AC0F764},2026-08-11T10:07:37-03:00,2026-08-11T03:00:00-03:00,Pago
882,Matriculado,CAN-004644-TRI,Luiz Felipe Soares,Avaliado,Ansiedade e Depressão: Intervenções em Terapia...,NaN,Cursos Livres - Faculdade Serra Dourada Lorena,2026-07-30T09:29:03-03:00,{D500D13C-128C-F111-8077-00224836BDFB},2026-07-30T09:30:10-03:00,2026-07-30T00:00:00-03:00,Pago
907,Matriculado,CAN-004619-TRI,Daniela Christina Toledo Werneck de Rezende,Avaliado,Ansiedade e Depressão: Intervenções em Terapia...,NaN,Cursos Livres - Faculdade Serra Dourada Lorena,2026-07-29T17:53:21-03:00,{2FF76983-8F8B-F111-8077-7CED8DB11FB7},2026-07-29T17:54:37-03:00,2026-07-29T18:03:34-03:00,Pago
1104,Matriculado,CAN-004416-TRI,Emmanuel Lamins Moreira Silva,Avaliado,Primeiros Socorros na Prática para Profissiona...,NaN,Cursos Livres - Faculdade Serra Dourada Lorena,2026-07-24T19:18:24-03:00,{37048995-AD87-F111-AB0F-70A8A5A98587},2026-07-24T19:19:27-03:00,2026-07-24T19:38:20-03:00,Pago
4056,Matriculado,CAN-001252-TRI,Paulo Victor Pereira Silva,Avaliado,Administração,NaN,PAGAMENTO / INTEGRAÇÃO TOTVS,2026-05-12T17:48:54-03:00,{D77E45F9-434E-F111-BEC7-7CED8DA8AD31},2026-05-12T17:49:40-03:00,2026-05-12T14:53:24-03:00,Pago

(8, 12)

In [64]:
df.to_excel('matriculas_na_captacao_que_nao_estao_na_planilha.xlsx', index=False)

## Matriculas que estão na planilha, mas não estão no CRM

In [69]:
# padronização das colunas de inscricao

matriculas['Número de Inscrição'] = matriculas['Número de Inscrição'].str.strip()

matriculas_inscricoes['Numero Inscricao'] = matriculas_inscricoes['Numero Inscricao'].str.strip()

In [70]:
df = matriculas.loc[~matriculas['Número de Inscrição'].isin(matriculas_inscricoes['Numero Inscricao'])]
# eliminar linhas em branco
df = df.dropna(subset=['Número de Inscrição'])
display(df)
df.shape

,CONSULTOR (a),DATA,Número de Inscrição,NOME,CELULAR,CPF (preencher apenas com números),CURSO,FORMA DE INGRESSO,1º Boleto alterado para 20/08?,% BOLSA CONCEDIDA,...,FORMA DE PAGAMNTO,QUANTIDADE DE PARCELAS,OBSERVAÇÃO,Unidade,Data e Hora,Unnamed: 18,DATA BOLETO AGOSTO (EXCEÇÕES),Unnamed: 15,Unnamed: 16,Unnamed: 17
1283,Daniel,2026-06-26,CAN-002642-TRI,Jenifer Ramires Moura Lopes,(12) 99668-6354,478.204.298-10,NUTRIÇÃO,TRANSFERENCIA,Não,0.65,...,PIX,1 VEZ,NaN,Lorena,NaT,NaN,NaT,NaN,NaN,NaT
1638,Karolaine,2026-08-14,CAN-005498-TRI,Igor Emanuel Martins Ribeiro,(94) 99106-7008,085.452.611-01,Análise e Desenvolvimento de Sistemas,Enem,NaN,0.7,...,Boleto,NaN,NaN,NaN,NaT,NaN,NaT,NaN,Canaã,2026-08-14 10:24:04.784

(2, 23)