In [1]:
from crm_leads import load_leads

In [11]:
leads = load_leads()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 250 registros
Página 18: 250 registros
Página 19: 250 registros
Página 20: 250 registros
Página 21: 250 registros
Página 22: 250 registros
Página 23: 250 registros
Página 24: 250 registros
Página 25: 250 registros
Página 26: 250 registros
Página 27: 250 registros
Página 28: 250 registros
Página 29: 250 registros
Página 30: 250 registros
Página 31: 250 registros
Página 32: 250 registros
Página 33: 250 registros
Página 34: 250 registros
Página 35: 250 registros
Página 36: 250 registros
Página 37: 250 registros
Página 38: 250 registros
Página 39: 250 registros
Página 40: 250 registros
Página 41: 250 registros
Página 42: 41 registros

In [12]:
leads.head(2)

,Inscrição Atual,cpf,Tabulação Realizada,Nome Completo,Nome,Sobrenome,Email,Celular,Telefone,ID Lead,...,Origem Lead,Canal,Nacionalidade,Estado Civil,Órgão Expedidor,RG,Cor/Raça,Sexo,Tabulação Lead,Detalhamento Tabulação
0,CAN-006284-TRI,159.420.756-97,Não,Maria Eduarda Veraldi Escada,Maria,Eduarda Veraldi Escada,eleandro.escada@hotmail.com,(34)99709-5227,(34)99709-5227,{1D1DE3FE-82A5-F111-AAAC-6045BD39BC63},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAN-006285-TRI,356.800.238-81,Sim,Mary Kenia Louzada Tavares,Mary,Kenia Louzada Tavares,mkeniatavareslouzada@gmail.com,(12)99665-9562,(12)99665-9562,{E9E836F4-82A5-F111-AAAD-7CED8DB11FB7},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# mapeando leads duplicados usando email + nome completo

duplicates = leads[leads.duplicated(subset=['Email', 'Nome Completo', 'Celular'], keep=False)]
duplicates = duplicates.sort_values(by = 'Nome Completo')
print(f"Total de leads duplicados: {len(duplicates)}")
display(duplicates)

Total de leads duplicados: 5

,Inscrição Atual,cpf,Tabulação Realizada,Nome Completo,Nome,Sobrenome,Email,Celular,Telefone,ID Lead,...,Origem Lead,Canal,Nacionalidade,Estado Civil,Órgão Expedidor,RG,Cor/Raça,Sexo,Tabulação Lead,Detalhamento Tabulação
710,NaN,NaN,Sim,mi,mi,NaN,milenacaeiro@icloud.com,5512992090003,NaN,{562A7F32-28A2-F111-B8DD-000D3AC0F764},...,Whatsapp - Formulário Meta,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,NaN,NaN,Não,mi,mi,NaN,milenacaeiro@icloud.com,5512992090003,NaN,{21CB7394-77A1-F111-B8DE-000D3AC0F764},...,Whatsapp - Formulário Meta,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,NaN,NaN,Não,neusivaldo ribeiro Rodrigues,neusivaldo,ribeiro Rodrigues,rneusivaldo@gmail.com,5594992303265,NaN,{6152614A-28A2-F111-B8DD-000D3AC0F764},...,AGR - Formulário Meta,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
788,NaN,NaN,Não,neusivaldo ribeiro Rodrigues,neusivaldo,ribeiro Rodrigues,rneusivaldo@gmail.com,5594992303265,NaN,{1EDA58AC-77A1-F111-B8DE-000D3AC0F764},...,AGR - Formulário Meta,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
952,NaN,NaN,Sim,neusivaldo ribeiro Rodrigues,neusivaldo,ribeiro Rodrigues,rneusivaldo@gmail.com,5594992303265,NaN,{60578993-B1A0-F111-B8DE-00224836B90D},...,AGR - Formulário Meta,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN,NaN