In [9]:
from crm_leads import load_leads

In [17]:
leads = load_leads()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 250 registros
Página 18: 250 registros
Página 19: 250 registros
Página 20: 250 registros
Página 21: 250 registros
Página 22: 250 registros
Página 23: 250 registros
Página 24: 250 registros
Página 25: 250 registros
Página 26: 250 registros
Página 27: 250 registros
Página 28: 250 registros
Página 29: 250 registros
Página 30: 250 registros
Página 31: 250 registros
Página 32: 250 registros
Página 33: 250 registros
Página 34: 250 registros
Página 35: 250 registros
Página 36: 250 registros
Página 37: 250 registros
Página 38: 250 registros
Página 39: 250 registros
Página 40: 15 registros

In [11]:
leads.head(2)

,Tabulação Realizada,Nome Completo,Sobrenome,Email,Celular,Telefone,ID Lead,Data Criação,Unidade Form,Situação Funil,...,Última Tabulação,Proprietário,Estado Civil,Nacionalidade,Órgão Expedidor,RG,Cor/Raça,Sexo,Tabulação Lead,Detalhamento Tabulação
0,Não,Vitória Kamilly da Silva de Oliveira,Vitória Kamilly da Silva de Oliveira,oliveira.vihksilva@gmail.com,(12)99751-4426,(12)99751-4426,{2B0D51E2-55A2-F111-B8DD-7CED8DB11FB7},NaT,Lorena,Potencial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Não,Teste Teste,Teste,teste@teste12.com,(31)99444-4444,(31)99444-4444,{F94AC8D2-53A2-F111-B8DD-000D3AC0F764},NaT,NaN,Matriculado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# mapeando leads duplicados usando email + nome completo

duplicates = leads[leads.duplicated(subset=['Email', 'Nome Completo', 'Celular'], keep=False)]
print(f"Total de leads duplicados: {len(duplicates)}")
display(duplicates[20:40])

Total de leads duplicados: 237

,Tabulação Realizada,Nome Completo,Sobrenome,Email,Celular,Telefone,ID Lead,Data Criação,Unidade Form,Situação Funil,...,Última Tabulação,Proprietário,Estado Civil,Nacionalidade,Órgão Expedidor,RG,Cor/Raça,Sexo,Tabulação Lead,Detalhamento Tabulação
116,Sim,Lidiane Silva,Silva,lihsilvasilva@yahoo.com,5512981156980,NaN,{C52A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
117,Sim,Magda morgato,morgato,Magdamorgatoo@gmail.com,5512981219476,NaN,{D92A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Adauri Marques Delfino Junior,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
118,Sim,Raissa Raissa,Raissa,raissasallesbraga@gmail.com,5512996889664,NaN,{9C2A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,Contato Errado,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
119,Sim,Jamilla Satim Vieira,Satim Vieira,jasatimvieira@hotmail.com,5512996751394,NaN,{6B2A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
120,Sim,giovana almeida,almeida,ga8867761@gmail.com,5535992683959,NaN,{7A2A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
121,Sim,Abençoada por Deus,por Deus,shirley-cristina33@hotmail.com,5512997653951,NaN,{892A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
122,Sim,Rosemary Rosemary,Rosemary,rosemaryfatimaluiz@gmail.com,5512997546930,NaN,{432A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
123,Sim,mi,NaN,milenacaeiro@icloud.com,5512992090003,NaN,{562A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,Contato Errado,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
126,Sim,Junior Ferreira,Ferreira,jocelioferreirajr@gmail.com,5512981530393,NaN,{2E2A7F32-28A2-F111-B8DD-000D3AC0F764},NaT,Lorena,Potencial,...,1º Atendimento,Daniel Faria Santos,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
142,Não,Sérgio Filho,Filho,montado.quilha.2w@icloud.com,556493084164,NaN,{1C68862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
144,Não,Crislane Dos Anjos,Dos Anjos,crislane_dosanjos@hotmail.com,5579996641872,NaN,{6F67862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
145,Não,Bernarda Santos,Santos,berndcarolina719@gmail.com,5595991757641,NaN,{8A67862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
146,Não,melissa neves b. mellado,neves b. mellado,melbinhote123@gmail.com,5521998381107,NaN,{A467862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
147,Não,Sandra Morais,Morais,smoraisad@hotmail.com,5571991615387,NaN,{4667862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
148,Não,Fernanda Alencar,Alencar,fernandalima240602@gmail.com,5595991295099,NaN,{5C67862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
149,Não,Bruna Batemarque,Batemarque,brunabatemarque@live.com,5531974007082,NaN,{1167862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
150,Não,Tauani Fausto Dias,Fausto Dias,nandatauani@gmail.com,5545999649700,NaN,{2967862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
151,Não,Jenn Lugtenburg,Lugtenburg,lugtenburgjenni@gmail.com,5553999887405,NaN,{3D178E26-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
152,Não,Potencia Fabito,Fabito,fabianbarrios88@gmail.com,5493718663693,NaN,{EE66862C-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN
153,Não,Lucas Halles,Halles,lucashalles@outlook.com.br,5555991347558,NaN,{F6168E26-28A2-F111-B8DD-000D3AC0F764},NaT,Medicina Lorena,Potencial,...,NaN,NaN,NaN,Brasil,NaN,NaN,NaN,NaN,NaN,NaN