In [1]:
from crm_leads_inscricao import load_leads

In [2]:
leads = load_leads()

Página 1: 1 registros

In [3]:
leads.head(2)

,Inscrição Atual,cpf,Tabulação Realizada,Nome Completo,Nome,Sobrenome,Email,Celular,ID Lead,Data Criação,Idade,Concurso Atual,Concurso de Origem,Data Nascimento,Oferta Atual,Situação Funil,Unidade Lead,Linha de Negócio
0,CAN-008732-TRI,627.033.880-80,Não,Karolaine Teste Pagamento,Karolaine,Teste Pagamento,627.033.880-80@gmail.com,(74)77663-6366,{0A5A11E4-189A-4CEE-B40D-BEBED36E6D4C},NaT,26,Histórico Ensino Médio - Faculdade Serra Doura...,Histórico Ensino Médio - Faculdade Serra Doura...,NaT,AGRONOMIA,Convocado,Altamira,Histórico do Ensino Médio Altamira

In [4]:
# mapeando leads duplicados usando email + nome completo

duplicates = leads[leads.duplicated(subset=['Email', 'Nome Completo', 'Celular'], keep=False)]
duplicates = duplicates.sort_values(by = 'Nome Completo')
print(f"Total de leads duplicados: {len(duplicates)}")
display(duplicates)

Total de leads duplicados: 0

Empty DataFrame
Columns: [Inscrição Atual, cpf, Tabulação Realizada, Nome Completo, Nome, Sobrenome, Email, Celular, ID Lead, Data Criação, Idade, Concurso Atual, Concurso de Origem, Data Nascimento, Oferta Atual, Situação Funil, Unidade Lead, Linha de Negócio]
Index: []